FROM node:lts

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Exposer le port utilisé par votre application
EXPOSE 4321

# Exécuter le serveur Node pour SSR
CMD ["node", "./dist/server/entry.mjs"]