version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:4321"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=${PUBLIC_API_URL}
      - HOST=0.0.0.0
      - PORT=${PORT_FRONTEND}

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT_BACKEND}
      - NODE_ENV=${NODE_ENV}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_TO=${EMAIL_TO}